CREATE SCHEMA relaciones AUTHORIZATION postgres;

GRANT ALL ON SCHEMA relaciones TO postgres;

CREATE TABLE relaciones.departamento (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(255) NULL,
	CONSTRAINT departamento_pkey PRIMARY KEY (id)
);

ALTER TABLE relaciones.departamento OWNER TO postgres;
GRANT ALL ON TABLE relaciones.departamento TO postgres;

CREATE TABLE relaciones.tarea (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	duracion int4 NOT NULL,
	nombre varchar(255) NULL,
	CONSTRAINT tarea_pkey PRIMARY KEY (id)
);

ALTER TABLE relaciones.tarea OWNER TO postgres;
GRANT ALL ON TABLE relaciones.tarea TO postgres;

CREATE TABLE relaciones.empleado (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	apellidos varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	nombre varchar(255) NOT NULL,
	id_departamento int4 NULL,
	CONSTRAINT empleado_pkey PRIMARY KEY (id),
	CONSTRAINT fk3gk585jldx1o6iod0f7ouseqk FOREIGN KEY (id_departamento) REFERENCES relaciones.departamento(id)
);

ALTER TABLE relaciones.empleado OWNER TO postgres;
GRANT ALL ON TABLE relaciones.empleado TO postgres;

CREATE TABLE relaciones.empleado_tareas (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	empleado_id int4 NULL,
	tareas_id int4 NULL,
	CONSTRAINT empleado_tareas_pkey PRIMARY KEY (id),
	CONSTRAINT fk27odufbj865r42wpu6vhu6lt8 FOREIGN KEY (tareas_id) REFERENCES relaciones.tarea(id),
	CONSTRAINT fkfuywhb55b8i4w3mcigean0h77 FOREIGN KEY (empleado_id) REFERENCES relaciones.empleado(id)
);

ALTER TABLE relaciones.empleado_tareas OWNER TO postgres;
GRANT ALL ON TABLE relaciones.empleado_tareas TO postgres;

CREATE TABLE relaciones.direccion (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	calle varchar(255) NULL,
	codigo_postal varchar(255) NULL,
	numero varchar(255) NULL,
	id_empleado int4 NULL,
	CONSTRAINT direccion_pkey PRIMARY KEY (id),
	CONSTRAINT ukj8vrdk39nnu18bm817gpiwlm7 UNIQUE (id_empleado),
	CONSTRAINT fkhpp4vy03xuxqdhkh2iernyqcj FOREIGN KEY (id_empleado) REFERENCES relaciones.empleado(id)
);

ALTER TABLE relaciones.direccion OWNER TO postgres;
GRANT ALL ON TABLE relaciones.direccion TO postgres;